- name : Configure Docker on test-server Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: Updating apt
    command : sudo apt-get update


  - name : Install Docker
    command : sudo apt-get install -y docker.io 

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name : Run the Bank application
    command: docker run -itd -p 8084:8082 prafullla/healthcare-app
