apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-deployment
 labels:
 app: healthcare
spec:
 selector:
 matchLabels:
 app: healthcare
 replicas: 1
 strategy:
 type: RollingUpdate
 template:
 metadata:
 labels:
 app: healthcare
 spec:
 containers:
 - name: healthcare
 image: prafullla/healthcare-app:latest
 ports:
 - containerPort: 80
