apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
data:
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-flannel-ds-amd64
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-flannel-ds-amd64
  template:
    metadata:
      labels:
        name: kube-flannel-ds-amd64
    spec:
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.12.0-amd64
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        - --iface={{ ansible_default_ipv4.interface }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
      - name: flannel-cfg
        configMap:
          name: kube-flannel-cfg
          optional: true
